### ISSUE TITLE
coil_id mismatch - pinda HFM data

### ISSUE THREAD

**Issue by agrawalch** [novelis-prod/Digital-CoE-Operations-Data---Public#69] opened 2020-06-29 13:20 UTC
@hebernogueira @guptaad 

The issue is that the coil_id=11638 value of 11719 in the coil_id column. The right value is 11638, but we see 11719 in the column cg_Gen_CoilId.

**Comment by hebernogueira** [comment] 2020-06-29 13:47
Same as issue #67

**Comment by guptaad** [comment] 2020-06-29 14:48
This is duplicate of #67. So closing this.

**Closed by guptaad** 2020-06-29 14:48 UTC
Labels: Priority #1, bug
